source 'https://github.com/CocoaPods/Specs.git'
platform :ios,'8.0'
inhibit_all_warnings!
use_frameworks!
target 'QM_FoldingTableViewDemo' do

#常用控件⬇️
pod 'YYCategories', '~> 1.0.4'                  #YY扩展
pod 'IQKeyboardManager', '~> 6.1.1'             #控制键盘的高度
pod 'Reachability', '~> 3.2'                    #网络监控插件
pod 'MBProgressHUD', '~> 1.1.0'                 #MB蒙版
pod 'MJRefresh', '~> 3.1.15.3'                  #刷新基类
pod 'MJExtension', '~> 3.0.15.1'                #数据转换
pod 'Masonry', '~> 1.1.0'                       #控件约束autolayout

#常用控件⤴️



end

#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        if target.name == 'ReactiveCocoa' || target.name == 'ReactiveSwift' || #target.name == 'TextFieldEffects'
#            target.build_configurations.each do |config|
#                config.build_settings['SWIFT_VERSION'] = '3.2'
#                end
#        else
#            target.build_configurations.each do |config|
#                config.build_settings['SWIFT_VERSION'] = '4.0'
#            end
#        end
#    end
#end
